# -*- coding: utf-8 -*-
"""aula3sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCFeYVCh3R65xFx5oIqZL-3WcdgKJM-P
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: LUCILA 

print ('Olá, ETE PORTO DIGITAL!')